<a href="https://colab.research.google.com/github/indrajit1984/Deep-learning/blob/code_basics/Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow practice


In [1]:
import tensorflow as tf
print (tf.__version__)

2.19.0


Tensorflow constant declaration

In [3]:
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [10]:
#create a matrix. Matrix has more then 1 diamention
matrix = tf.constant([[10,10],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7, 10]], dtype=int32)>

create randor vector

In [11]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [12]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

To randomize the inpur data stream in a NN network, Vector/Tensor should be shuffled.
Lets shuffle a Vector/Tensor

In [14]:
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

Notice that `random_2` is identical to `random_1` because the generator was re-initialized with the same seed. If you want a *different* set of random numbers with a different seed, you would use a different seed value.

In [25]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [26]:
tf.zeros([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>