<a href="https://colab.research.google.com/github/indrajit1984/Deep-learning/blob/code_basics/Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow practice


In [8]:
import tensorflow as tf
import numpy as np
print (tf.__version__)

2.19.0


Tensorflow constant declaration

In [3]:
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [10]:
#create a matrix. Matrix has more then 1 diamention
matrix = tf.constant([[10,10],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7, 10]], dtype=int32)>

create randor vector

In [6]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal([3,2])
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [12]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

To randomize the inpur data stream in a NN network, Vector/Tensor should be shuffled.
Lets shuffle a Vector/Tensor

In [14]:
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

Notice that `random_2` is identical to `random_1` because the generator was re-initialized with the same seed. If you want a *different* set of random numbers with a different seed, you would use a different seed value.

In [25]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [27]:
five_bi_six = tf.zeros([5,6])
five_bi_six

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [29]:
five_bi_six[:2,:2]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

### Understanding `tf.newaxis`

`tf.newaxis` is used to increase the dimension of an existing tensor (or NumPy array) by one unit. It's essentially a placeholder that creates a new axis (dimension) at the position where it's inserted. This is particularly useful when you need to broadcast tensors for element-wise operations or when a function expects a tensor of a specific rank (number of dimensions).

In [30]:
import tensorflow as tf

# Let's start with a 1-D tensor
vector = tf.constant([1, 2, 3, 4])
print("Original Vector:", vector.numpy())
print("Shape of Original Vector:", vector.shape)
print("Number of dimensions (rank):", vector.ndim)

Original Vector: [1 2 3 4]
Shape of Original Vector: (4,)
Number of dimensions (rank): 1


### Example: Adding a new axis

In [31]:
# 1. Adding a new axis at the beginning (making it a row vector, shape (1, 4))
reshaped_vector_1 = vector[tf.newaxis, :]
print("\nReshaped Vector (tf.newaxis, :):")
print(reshaped_vector_1.numpy())
print("Shape:", reshaped_vector_1.shape)
print("Number of dimensions (rank):", reshaped_vector_1.ndim)


Reshaped Vector (tf.newaxis, :):
[[1 2 3 4]]
Shape: (1, 4)
Number of dimensions (rank): 2


In [32]:
# 2. Adding a new axis at the end (making it a column vector, shape (4, 1))
reshaped_vector_2 = vector[:, tf.newaxis]
print("\nReshaped Vector (:, tf.newaxis):")
print(reshaped_vector_2.numpy())
print("Shape:", reshaped_vector_2.shape)
print("Number of dimensions (rank):", reshaped_vector_2.ndim)


Reshaped Vector (:, tf.newaxis):
[[1]
 [2]
 [3]
 [4]]
Shape: (4, 1)
Number of dimensions (rank): 2


In [33]:
# You can also use tf.expand_dims for the same purpose, which is often more explicit.
# Example: Adding a dimension at index 0 (beginning)
expanded_vector_1 = tf.expand_dims(vector, axis=0)
print("\nExpanded Vector (tf.expand_dims, axis=0):")
print(expanded_vector_1.numpy())
print("Shape:", expanded_vector_1.shape)

# Example: Adding a dimension at index 1 (end)
expanded_vector_2 = tf.expand_dims(vector, axis=1)
print("\nExpanded Vector (tf.expand_dims, axis=1):")
print(expanded_vector_2.numpy())
print("Shape:", expanded_vector_2.shape)


Expanded Vector (tf.expand_dims, axis=0):
[[1 2 3 4]]
Shape: (1, 4)

Expanded Vector (tf.expand_dims, axis=1):
[[1]
 [2]
 [3]
 [4]]
Shape: (4, 1)


In [4]:
C =tf.constant([7. , 8.1])
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([7. , 8.1], dtype=float32)>

In [5]:
E=tf.cast(C, dtype=tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([7. , 8.1], dtype=float16)>

In essence, `tf.newaxis` provides a concise syntax within slicing operations to achieve the same result as `tf.expand_dims`.

In [10]:
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([98, 29, 96, 22, 31, 35, 53,  7, 16, 32, 31, 30, 95, 56, 17, 18, 57,
       47, 47, 84, 62, 30, 78, 55, 38, 72, 75, 49, 35, 34, 71, 96, 86, 97,
        7, 73,  9,  9, 17, 62, 76, 30, 47,  4, 21,  2, 41, 32, 24, 32])>

In [14]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [16]:
np.std(E)

np.float64(27.747612509907945)

In [17]:
np.max(E)

np.int64(98)

In [22]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.74761199951172>

### **One hot encoding**

In [23]:
one_list = tf.constant([0,1,2,3])
one_list

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [24]:
tf.one_hot(one_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>